### ISSUE TITLE
Username and Password Page

### ISSUE THREAD

**Issue by gpantalone** [rk1998/pickleratsapp#2]
This page should have 2 fields labelled for username and password respectively. It should also have 2 buttons: a login button that checks the values in username and password against our default user. If they are equal to the required values we should take the user to the Logged In page. If they are not we should Flash a message alert: "Incorrect username or password". The second button should be a cancel button that returns the user to the welcome screen

**Comment by rk1998** [comment]
I added a cancel button that takes the user back to the home screen. Also added a pop up message that alerts the user when he or she puts in a wrong password or username
